/*
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms
 * will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do
 * not exceed four million, find the sum of the even-valued terms.
 *
 * Author: Clifton Roberts
 * Date: 11 November 2016
 */

#include <iostream>

using namespace std;

int main()
{
	const unsigned int LIMIT = 4000000;

	unsigned int sum = 0;
	unsigned int a = 1;
	unsigned int b = 1;
	unsigned int c = 0;

	while (b < LIMIT)
	{
		c = a + b;

		if (c < LIMIT && c % 2 == 0)
		{
			sum += c;
		}

		a = b;
		b = c;
	}

	cout << sum << endl;

	cin.get();
	return 0;
}
